version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./client/.env
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "6500:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
